# mybatis配置
spring:
  profiles: commonDal
mybatis:
  mapper-locations: classpath:com/bla/imagefetch/common/dal/imagefactory/auto/mapper/imagefactory/*.xml    # mapper映射文件位置
  type-aliases-package: com.bla.imagefetch.common.dal.imagefactory.auto.mapper    # 实体类所在的位置
logging:
  level:
    com:
      bla:
        imagefetch:
          common:
            dal:
              imagefactory:
                auto: debug
---
# 数据源
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/imagefactory_test?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

imageTaskRunWithStart: false                     # 自定义:禁用图片任务自启动
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/imagefactory?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

imageTaskRunWithStart: true                      # 自定义:禁用图片任务自启动